### ISSUE TITLE
attach failed with TimeoutError exception

### ISSUE THREAD

**Issue by friendwu** [google/pyringe#26]
I'm running pyringe to try to attach to one python process on Mac platform, and it fails all the time.

Using pyringe git HEAD code instead of PYPI package.
Gdb version: 8.1

Here is the trace:

> Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "pyringe/repl.py", line 161, in Attach
    self.inferior.Reinit(pid)
  File "pyringe/inferior.py", line 484, in Reinit
    self.__init__(pid, auto_symfile_loading, architecture=self.arch)
  File "pyringe/inferior.py", line 456, in __init__
    self.StartGdb()
  File "pyringe/inferior.py", line 503, in StartGdb
    self._gdb.Attach(self.position)
  File "pyringe/inferior.py", line 200, in <lambda>
    return lambda *args, **kwargs: self._Execute(name, *args, **kwargs)
  File "pyringe/inferior.py", line 342, in _Execute
    result_string = self._Recv(timeout)
  File "pyringe/inferior.py", line 429, in _Recv
    raise TimeoutError()
TimeoutError
==> pid:[71164] #threads:[0] current thread:[None]

**Comment by NetWilliam** [comment]
I have the same error while debugging some pydoop and celery code.....
