### ISSUE TITLE
ModuleNotFoundError: No module named 'inferior'

### ISSUE THREAD

**Issue by pirate** [google/pyringe#27]
- OS: `Ubuntu 19.04`
- Arch: `Linux carrot 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```bash
➜ apt install gdb python-dbg python2.7-dbg
➜ pip install --no-cache-dir pyringe
Collecting pyringe
  Using cached https://files.pythonhosted.org/packages/7c/c6/6cef124c38227ece01350414c7866727179d17f64b88b8bf513386c0e4be/pyringe-1.0.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jearzn7v/pyringe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jearzn7v/pyringe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-jearzn7v/pyringe/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jearzn7v/pyringe/setup.py", line 18, in <module>
        import pyringe
      File "/tmp/pip-install-jearzn7v/pyringe/pyringe/__init__.py", line 17, in <module>
        import inferior
    ModuleNotFoundError: No module named 'inferior'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

However, installing via git repo worked fine, so it looks like it's an issue with the pip package and is due to missing dependencies / bad system setup:
```bash
➜ git clone https://github.com/google/pyringe.git
➜ cd pyringe
➜ python setup.py install
➜ python -m pyringe
Pyringe (Python 2.7.15) on linux2
For a list of debugger commands, try "help()". (python's help is available as pyhelp.)
==> pid:[None] #threads:[0] current thread:[None]
>>>
```

**Comment by TehMillhouse** [comment]
Your `pip` seems to be the python3 pip, but your `python` seems to be python2. Could you try the pip route again, this time explicitly using `pip2`?

**Comment by pirate** [comment]
That worked, thanks.
